using MoviesGallery.ViewModels;
using MoviesGallery.ViewModels.Common;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MoviesGallery.Server.Services
{
    public interface IMoviesGalleryService
    {
        Task<string> CreateCategoryAsync(CreateCategoryVM categoryVM);
        Task<string> CreateCountryAsync(CreateCountryVM countryVM);
        Task<string> CreateDirectorAsync(CreateDirectorVM directorVM);
        Task<string> CreateDownloadLinkAsync(CreateDownloadLinkVM downloadLinkVM);
        Task<string> CreateFilmStarAsync(CreateFilmStarVM filmStarVM);
        Task<string> CreateLanguageAsync(CreateLanguageVM languageVM);
        Task<string> CreateMovieAsync(CreateMovieVM movieVM);
        Task<string> CreateQualityAsync(CreateQualityVM qualityVM);
        Task<string> CreateScreenshotAsync(CreateScreenshotVM screenshotVM);
        Task<string> CreateSlideShowAsync(CreateSlideShowVM slideShowVM);
        Task<string> DeleteCategoryAsync(Guid id);
        Task<string> DeleteCountryAsync(Guid id);
        Task<string> DeleteDirectorAsync(Guid id);
        Task<string> DeleteDownloadLinkAsync(Guid id);
        Task<string> DeleteFilmStarAsync(Guid id);
        Task<string> DeleteLanguageAsync(Guid id);
        Task<string> DeleteMovieAsync(Guid id);
        Task<string> DeleteQualityAsync(Guid id);
        Task<string> DeleteScreenshotAsync(Guid id);
        Task<string> DeleteSlideShowAsync(Guid id);
        Task<List<CategoryVM>> ReadCategoryAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadCategoryAsync(Guid id);
        Task<CategoryVM> ReadCategoryAsync(Guid id, bool include);
        Task<CategoryVM> ReadCategoryAsync(string name, bool include);
        Task<List<CategoryVM>> ReadCategoryAsync(string name, bool include, int noOfRecords = 0);
        Task<List<CountryVM>> ReadCountryAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadCountryAsync(Guid id);
        Task<CountryVM> ReadCountryAsync(Guid id, bool include);
        Task<CountryVM> ReadCountryAsync(string name, bool include);
        Task<List<CountryVM>> ReadCountryAsync(string name, bool include, int noOfRecords = 0);
        Task<List<DirectorVM>> ReadDirectorAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadDirectorAsync(Guid id);
        Task<DirectorVM> ReadDirectorAsync(Guid id, bool include);
        Task<DirectorVM> ReadDirectorAsync(string name, bool include);
        Task<List<DirectorVM>> ReadDirectorAsync(string name, bool include, int noOfRecords = 0);
        Task<List<DownloadLinkVM>> ReadDownloadLinkAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadDownloadLinkAsync(Guid id);
        Task<DownloadLinkVM> ReadDownloadLinkAsync(Guid id, bool include);
        Task<DownloadLinkVM> ReadDownloadLinkAsync(string title, bool include);
        Task<List<DownloadLinkVM>> ReadDownloadLinkAsync(string title, bool include, int noOfRecords = 0);
        Task<List<FilmStarVM>> ReadFilmStarAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadFilmStarAsync(Guid id);
        Task<FilmStarVM> ReadFilmStarAsync(Guid id, bool include);
        Task<FilmStarVM> ReadFilmStarAsync(string name, bool include);
        Task<List<FilmStarVM>> ReadFilmStarAsync(string name, bool include, int noOfRecords = 0);
        Task<List<LanguageVM>> ReadLanguageAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadLanguageAsync(Guid id);
        Task<LanguageVM> ReadLanguageAsync(Guid id, bool include);
        Task<LanguageVM> ReadLanguageAsync(string name, bool include);
        Task<List<LanguageVM>> ReadLanguageAsync(string name, bool include, int noOfRecords = 0);
        Task<List<MovieVM>> ReadMovieAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadMovieAsync(Guid id);
        Task<MovieVM> ReadMovieAsync(Guid id, bool include);
        Task<MovieVM> ReadMovieAsync(string title, bool include);
        Task<List<MovieVM>> ReadMovieAsync(string title, bool include, int noOfRecords = 0);
        Task<List<QualityVM>> ReadQualityAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadQualityAsync(Guid id);
        Task<QualityVM> ReadQualityAsync(Guid id, bool include);
        Task<QualityVM> ReadQualityAsync(string name, bool include);
        Task<List<QualityVM>> ReadQualityAsync(string name, bool include, int noOfRecords = 0);
        Task<List<ScreenshotVM>> ReadScreenshotAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadScreenshotAsync(Guid id);
        Task<ScreenshotVM> ReadScreenshotAsync(Guid id, bool include);
        Task<ScreenshotVM> ReadScreenshotAsync(string title, bool include);
        Task<List<ScreenshotVM>> ReadScreenshotAsync(string title, bool include, int noOfRecords = 0);
        Task<List<SlideShowVM>> ReadSlideShowAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadSlideShowAsync(Guid id);
        Task<SlideShowVM> ReadSlideShowAsync(Guid id, bool include);
        Task<SlideShowVM> ReadSlideShowAsync(string title, bool include);
        Task<List<SlideShowVM>> ReadSlideShowAsync(string title, bool include, int noOfRecords = 0);
        Task<string> UpdateCategoryAsync(UpdateCategoryVM categoryVM);
        Task<string> UpdateCountryAsync(UpdateCountryVM countryVM);
        Task<string> UpdateDirectorAsync(UpdateDirectorVM directorVM);
        Task<string> UpdateDownloadLinkAsync(UpdateDownloadLinkVM downloadLinkVM);
        Task<string> UpdateFilmStarAsync(UpdateFilmStarVM filmStarVM);
        Task<string> UpdateLanguageAsync(UpdateLanguageVM languageVM);
        Task<string> UpdateMovieAsync(UpdateMovieVM movieVM);
        Task<string> UpdateQualityAsync(UpdateQualityVM qualityVM);
        Task<string> UpdateScreenshotAsync(UpdateScreenshotVM screenshotVM);
        Task<string> UpdateSlideShowAsync(UpdateSlideShowVM slideShowVM);
    }
}