using MoviesGallery.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MoviesGallery.Repository
{
    public interface IMoviesGalleryRepository
    {
        Task<string> CreateCategoryAsync(Category category);
        Task<string> CreateCountryAsync(Country country);
        Task<string> CreateDirectorAsync(Director director);
        Task<string> CreateDownloadLinkAsync(DownloadLink downloadLink);
        Task<string> CreateFilmStarAsync(FilmStar filmStar);
        Task<string> CreateLanguageAsync(Language language);
        Task<string> CreateMovieAsync(Movie movie);
        Task<string> CreateQualityAsync(Quality quality);
        Task<string> CreateScreenshotAsync(Screenshot screenshot);
        Task<string> CreateSlideShowAsync(SlideShow slideShow);
        Task<string> DeleteCategoryAsync(Guid id);
        Task<string> DeleteCountryAsync(Guid id);
        Task<string> DeleteDirectorAsync(Guid id);
        Task<string> DeleteDownloadLinkAsync(Guid id);
        Task<string> DeleteFilmStarAsync(Guid id);
        Task<string> DeleteLanguageAsync(Guid id);
        Task<Movie> DeleteMovieAsync(Guid id);
        Task<string> DeleteQualityAsync(Guid id);
        Task<Screenshot> DeleteScreenshotAsync(Guid id);
        Task<SlideShow> DeleteSlideShowAsync(Guid id);
        Task<List<Category>> ReadCategoryAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadCategoryAsync(Guid id);
        Task<Category> ReadCategoryAsync(Guid id, bool include);
        Task<Category> ReadCategoryAsync(string name, bool include);
        Task<List<Category>> ReadCategoryAsync(string name, bool include, int noOfRecords = 0);
        Task<List<Country>> ReadCountryAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadCountryAsync(Guid id);
        Task<Country> ReadCountryAsync(Guid id, bool include);
        Task<Country> ReadCountryAsync(string name, bool include);
        Task<List<Country>> ReadCountryAsync(string name, bool include, int noOfRecords = 0);
        Task<List<Director>> ReadDirectorAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadDirectorAsync(Guid id);
        Task<Director> ReadDirectorAsync(Guid id, bool include);
        Task<Director> ReadDirectorAsync(string name, bool include);
        Task<List<Director>> ReadDirectorAsync(string name, bool include, int noOfRecords = 0);
        Task<List<DownloadLink>> ReadDownloadLinkAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadDownloadLinkAsync(Guid id);
        Task<DownloadLink> ReadDownloadLinkAsync(Guid id, bool include);
        Task<DownloadLink> ReadDownloadLinkAsync(string title, bool include);
        Task<List<DownloadLink>> ReadDownloadLinkAsync(string title, bool include, int noOfRecords = 0);
        Task<List<FilmStar>> ReadFilmStarAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadFilmStarAsync(Guid id);
        Task<FilmStar> ReadFilmStarAsync(Guid id, bool include);
        Task<FilmStar> ReadFilmStarAsync(string name, bool include);
        Task<List<FilmStar>> ReadFilmStarAsync(string name, bool include, int noOfRecords = 0);
        Task<List<Language>> ReadLanguageAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadLanguageAsync(Guid id);
        Task<Language> ReadLanguageAsync(Guid id, bool include);
        Task<Language> ReadLanguageAsync(string name, bool include);
        Task<List<Language>> ReadLanguageAsync(string name, bool include, int noOfRecords = 0);
        Task<List<Movie>> ReadMovieAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadMovieAsync(Guid id);
        Task<Movie> ReadMovieAsync(Guid id, bool include);
        Task<Movie> ReadMovieAsync(string title, bool include);
        Task<List<Movie>> ReadMovieAsync(string title, bool include, int noOfRecords = 0);
        Task<List<Quality>> ReadQualityAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadQualityAsync(Guid id);
        Task<Quality> ReadQualityAsync(Guid id, bool include);
        Task<Quality> ReadQualityAsync(string name, bool include);
        Task<List<Quality>> ReadQualityAsync(string name, bool include, int noOfRecords = 0);
        Task<List<Screenshot>> ReadScreenshotAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadScreenshotAsync(Guid id);
        Task<Screenshot> ReadScreenshotAsync(Guid id, bool include);
        Task<Screenshot> ReadScreenshotAsync(string title, bool include);
        Task<List<Screenshot>> ReadScreenshotAsync(string title, bool include, int noOfRecords = 0);
        Task<List<SlideShow>> ReadSlideShowAsync(bool include, int noOfRecords = 0);
        Task<bool> ReadSlideShowAsync(Guid id);
        Task<SlideShow> ReadSlideShowAsync(Guid id, bool include);
        Task<SlideShow> ReadSlideShowAsync(string title, bool include);
        Task<List<SlideShow>> ReadSlideShowAsync(string title, bool include, int noOfRecords = 0);
        Task<string> UpdateCategoryAsync(Category category);
        Task<string> UpdateCountryAsync(Country country);
        Task<string> UpdateDirectorAsync(Director director);
        Task<string> UpdateDownloadLinkAsync(DownloadLink downloadLink);
        Task<string> UpdateFilmStarAsync(FilmStar filmStar);
        Task<string> UpdateLanguageAsync(Language language);
        Task<string> UpdateMovieAsync(Movie movie);
        Task<string> UpdateQualityAsync(Quality quality);
        Task<string> UpdateScreenshotAsync(Screenshot screenshot);
        Task<string> UpdateSlideShowAsync(SlideShow slideShow);
    }
}